### ISSUE TITLE
Добавить файлы для деплоя

### ISSUE THREAD

**Issue by ilon-mars** [Gelikk99/free-creative#2]
1. Создать в корне папку `.github/workflows` (прямо так с точкой и писать)
2. Создать в этой папке 2 файла:
- static.yml
```
# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
```

-preview.yml
```
name: Deploy PR previews
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize    
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@v1.4.3
        with:
          preview-branch: main
          source-dir: .
          umbrella-dir: pr-preview
          action: auto
```

В settings -> pages -> Build and deployment выбрать Source: GitHub actions
